---
- name: Install Java 1.8
  hosts: all
  become: yes
  tasks:
    - name: Install Java 1.8
      package:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-8-jdk  # For Debian/Ubuntu
        - java-1.8.0-openjdk  # For RHEL/CentOS

    - name: Verify Java Installation
      command: java -version
      register: java_version

    - name: Display Java Version
      debug:
        var: java_version.stdout
